<?php

namespace MyApp\UserBundle\Repository;

/**
 * AchatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchatsRepository extends \Doctrine\ORM\EntityRepository
{
}
