<?php

namespace MyApp\UserBundle\Repository;

/**
 * BoutiquesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiquesRepository extends \Doctrine\ORM\EntityRepository
{
}
