<?php

namespace MyApp\UserBundle\Repository;

/**
 * carteFidelitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carteFidelitesRepository extends \Doctrine\ORM\EntityRepository
{
}
