<?php

namespace MyApp\UserBundle\Repository;

/**
 * LivraisonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonsRepository extends \Doctrine\ORM\EntityRepository
{
}
