<?php

namespace MyApp\UserBundle\Repository;

/**
 * OffresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffresRepository extends \Doctrine\ORM\EntityRepository
{
}
