<?php

namespace MyApp\UserBundle\Repository;

/**
 * ReclamationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationsRepository extends \Doctrine\ORM\EntityRepository
{
}
